### ISSUE TITLE
Visibility of References (plugin-references)

### ISSUE THREAD

**Issue by i2p-lbt** [fedwiki/wiki#66]
It took me a while to find out that references are references, after I first wondered about how pages are composed. Turned out I wasn't able to see the slightly blue background, which would have helped me quite a lot in identifying these are specific elements of the page. I was looking at a (tiny) bit of an angle at the display which made all the difference here. As this the first time that I notice this making a difference, I assume it might be helpful to highlight these a bit more distinctively. 

I played around with some settings and after all want to suggest to highlight the external links created by the references-plugin in the same way external pages are highlighted. Is that a sound idea in the sense of conformity?

I used the same box-shadow but had to make the border a bit smaller and found an indentation of the paragraph further helpful. The CSS code I used was this (instead of the `background-color: #F0F8FF;` that was there):

```css
.reference {
    box-shadow: 0px 0px 10px 0px rgba(0, 180, 220, 0.5) inset;
    margin-left: 15px;
    padding: 7px;
}
```

The paragraph within gets an inline style set by the [reference-plugin](https://github.com/fedwiki/wiki-plugin-reference/blob/master/client/reference.coffee) in line 15. This needs another setting in addition with the above, otherwise the top looks "ugly". Either change it to the following there (if inline is actually desired - plugin-architecture or something?) or move it to the css as well while at it with something like this:

```css
 .reference p {
    margin-top: 3px;
    margin-bottom: 3px;    
}
```

The latter is not tested, but `.reference p`should address the paragraph within the reference-div, right? I would have made this and created a pull-request after testing, but I wasn't able to find any source for the CSS file, yet. Is that maybe generated on-the-fly or something?
